#' Example Post-QC TCR contigs that would be generated within ECLIPSE
#' and passed to findThreeChainClones.
#'
#' @format A data frame in the all_contig_annotations.csv format
#' that is produced by cellranger vdj.
#'
#' @source Example data
"post_qc_contigs"

#' Example minimal Seurat object without TCR information.
#'
#' @format A Seurat object.
#'
#' @source Example data
"test_seurat"

#' Example Seurat object with TCR information generated by running
#' the ECLIPSE function.
#'
#' @format A Seurat object.
#'
#' @source Example data
"test_seurat_with_tcr"

#' Example small Seurat object without TCR information.
#'
#' @format A Seurat object.
#'
#' @source Example data
"vignette_object"
